### PR TITLE
Check manifest with Antifreeze

### PR DESCRIPTION
**Pull request by odlp**
Hi,

Thanks for autopilot, it's really handy. Please consider this PR which adds a reference to [Antifreeze](https://github.com/odlp/antifreeze). 

I created this with Autopilot in mind; a pre-flight check to verify the app you're about to replace doesn't have any environment variables or services which are missing from the manifest file.

### CODE REVIEW

**Comment by vito** [comment]
Neat! @xoebus you OK with this?

**Comment by xoebus** [comment]
Yah, looks great.

**Comment by vito** [comment]
Merging then - thanks @odlp!

**Comment by odlp** [comment]
Cheers @vito & @xoebus

**Pull request merged**
